# Setup
title:        Choonguri's Read & Wirte
tagline:      ""
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Choonguri
  url:        http://choonguri.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

disqus_shortname: choonguri
