# Setup
title:        Choonguri's Blog
tagline:      Just Do It!
baseurl:      "/blog"
paginate:     5

# About/contact
author:
  name:       Choonguri
  url:        http://choonguri.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
